version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - uploads:/app/uploads
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start:dev"

volumes:
  postgres_data:
  uploads:
